### ISSUE TITLE
An issue about the SYNTHIA dataset

### ISSUE THREAD

**Issue by songjiaxina** [ethz-asl/x-view#2]
Thanks for your great paper. Recently I am also doing some work about relocalization. But when I use the   SYNTHIA dataset , I tried to get the whole global map by using the depth image and the camera pose provided of every frame. But It always fails. And itproves the depth image is correct.  So I suspect that the  camera coordinate system of the SYNTHIA dataset is inconsistent of the usual one. Since you have used this dataset in your paper,Could you please tell me some reasons why this occurs? I am really bothered.

**Comment by MantangGuo** [comment]
I have the same suspicion as yours that the camera pose is not correct. Would you mind telling me how you fix this problem?

**Comment by gawela** [comment]
Yes, there are some strange conversions happening in the provided data. We have written a package that lets you convert the raw SYNTHIA data into bag files with correct projections [here](https://github.com/ethz-asl/synthia_to_rosbag). You have to apply some rotations as to [this](https://github.com/ethz-asl/synthia_to_rosbag/blob/master/src/synthia_parser.cpp#L222). I hope this helps.

**Comment by MantangGuo** [comment]
> Yes, there are some strange conversions happening in the provided data. We have written a package that lets you convert the raw SYNTHIA data into bag files with correct projections [here](https://github.com/ethz-asl/synthia_to_rosbag). You have to apply some rotations as to [this](https://github.com/ethz-asl/synthia_to_rosbag/blob/master/src/synthia_parser.cpp#L222). I hope this helps.

Thank you very much for the reply and code. I'm new to ROSbag and C++,  and just want the correct camera pose of SYNTHIA to do other task which is unrelated to the project you provide. 
Could you just tell me how to convert the camera pose provided by SYNTHIA into the correct one? I just follow the instruction provided by SYNTHIA, i.e., 

```matlab
vec = load('filename.txt');
RT = reshape(vec, 4, 4);
```

and load the SYNTHIA camera pose by using Python, i.e., 

```python 
camera_extrinsics = open(os.path.join(data_path,scene_name,'CameraParams','Stereo_Left','Omni_L','{:06d}.txt'.format(ind_view)),'r').read().split()
camera_extrinsics = np.array([float(i) for i in camera_extrinsics])
camera_extrinsics = camera_extrinsics.reshape(4,4).transpose(1,0)
R = camera_extrinsics[0:3,0:3]
T = camera_extrinsics[0:3,3]
camera_intrinsics = open(os.path.join(data_path,scene_name,'CameraParams','intrinsics.txt'),'r').read().split()
camera_intrinsics = np.array([float(i) for i in camera_intrinsics])
K= np.array([[camera_intrinsics[0],0, camera_intrinsics[1]],
            [0, camera_intrinsics[0], camera_intrinsics[2]],
            [0,0,1]])
```

But I got the wrong results when apply to my task. And I'm pretty sure the camera pose is not accurate.
